# Generated by Django 5.1.4 on 2024-12-12 01:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryIncident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity_level', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('sanction', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], default='Minor', max_length=20)),
                ('reported_by', models.TextField(max_length=200)),
            ],
        ),
    ]
