# Generated by Django 5.1.2 on 2024-12-09 12:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_transaction_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeverityLevel',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_description', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grade_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(12)])),
                ('section', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('POD', 'Prefect of Discipline'), ('ADMIN', 'Administrator')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaryIncident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.severitylevel')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to='users.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('sanction_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.disciplinaryincident')),
                ('severity_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.severitylevel')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_sanctions', to='users.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
