# Generated by Django 5.1.4 on 2024-12-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_severitylevel_student_staff_disciplinaryincident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaryincident',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='disciplinaryincident',
            name='reported_by',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='disciplinaryincident',
            name='severity_level',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='disciplinaryincident',
            name='student',
            field=models.TextField(max_length=50),
        ),
    ]
